modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-elytraportalfix/issues"
license = "ARR"

[[mods]]
modId = "elytraportalfix"
version = "${version}"
displayName = "Elytra Portal Fix"
authors = "mahmudindev"
description = '''
Fix player cannot use portal while flying with elytra.
'''
logoFile = "assets/elytraportalfix/icon.png"

[[dependencies.elytraportalfix]]
modId = "neoforge"
type = "required"
versionRange = "[21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.elytraportalfix]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "elytraportalfix.mixins.json"
